apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: tfm-mgm
      appName: tf-bajafactura-model
      appTypes: tensorflow-serving-s2i
      appid: tf-serving-tf-bajafactura-model
    name: tf-bajafactura-model
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: tf-bajafactura-model:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: None
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: tf-serving-s2i:latest
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers: []
  status:
    lastVersion: 4
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: tfm-mgm
    name: topic-model-streaming
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: topic-model-streaming:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.4
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers: []
  status:
    lastVersion: 30
kind: List
metadata:
