apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:    labels:
      app: tfm-mgm
      service: lt-tfm-calls
    name: lt-tfm-calls
  spec:
    resourceVersion: 172.30.153.228
    ports:
    - name: 5010-tcp
      port: 5010
      protocol: TCP
      targetPort: 5010
    selector:
      deploymentconfig: lt-tfm-calls
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:    labels:
      app: tfm-mgm
    name: stream-predicter
  spec:
    clusterIP: 172.30.112.219
    ports:
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: stream-predicter
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:    labels:
      app: tfm-mgm
    name: stream-sequencer
  spec:
    clusterIP: 172.30.51.58
    ports:
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: stream-sequencer
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:    labels:
      app: tfm-mgm
    name: stream-tokenizer
  spec:
    clusterIP: 172.30.107.88
    ports:
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: stream-tokenizer
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:    labels:
      app: tfm-mgm
      appName: tf-bajafactura-model
      appTypes: tensorflow-serving-s2i
      appid: tf-serving-tf-bajafactura-model
    name: tf-bajafactura-model
  spec:
    clusterIP: 172.30.62.160
    ports:
    - name: 8501-tcp
      port: 8501
      protocol: TCP
      targetPort: 8501
    selector:
      deploymentconfig: tf-bajafactura-model
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
